version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
      PGDATA: '/data/postgres'
    volumes:
       - './postgres:/data/postgres'
    ports:
      - '5432:5432'
    networks:
      - 'postgres'
    restart: 'always'

  
  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    volumes:
       - './pgadmin:/root/.pgadmin'
    ports:
      - '5050:80'
    networks:
      - 'postgres'
    restart: 'always'


  redis:
    container_name: 'redis'
    image: 'redis'
    volumes:
      - './redis:/var/lib/redis'
    ports:
      - '6379:6379'


  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'


  # sysctl -w vm.max_map_count=262144
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.4'
    environment:
      - 'node.name=es01'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      nproc: '65535'
      memlock:
        soft: '-1'
        hard: '-1'
    volumes:
      - './elasticsearch/data:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
      - '9300:9300'



networks:
  postgres:
    driver: bridge
